name: Newman Run

on:
  push:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: api_tests.json
  cypress-run:
    runs-on: ubuntu-16.04
    needs: [newman]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
